// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsejhfhvbjcorkqzokfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzZWpoZmh2Ympjb3JrcXpva2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjU5NzAsImV4cCI6MjA3Mzg0MTk3MH0.ktvqtl2CMkodmHOR4-GwQX5AFWin8Xj8t-yQh1SK7JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});